FROM balenalib/intel-nuc-golang:1.12.4-stretch-20190511 as build

RUN apt-get update
RUN apt-get install curl

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

WORKDIR /go/src/balena-maintenance-windows

COPY ./Gopkg.lock .
COPY ./Gopkg.toml .
COPY ./main.go .
COPY ./balenaapi ./balenaapi
COPY ./timeutils ./timeutils
COPY ./lockfile ./lockfile

RUN dep ensure

CMD ["go", "test", "./..."]
